# Project name and description
project_name: "cherry_event_indexer"
description: "Cherry event indexing and data processing pipeline"

# Data source configuration
providers:
  my_sqd_provider:
    kind: sqd
    config:
      url: https://portal.sqd.dev/datasets/ethereum-mainnet

writers:
  my_local_writer:
    kind: local_parquet
    config:
      path: ""
  aws_wrangler_s3:
    kind: aws_wrangler_s3
    config:
      endpoint: http://localhost:9000
      database: blockchain
      use_boto3: true
      s3_path: blockchain-data/aws-wrangler-s3
      region: "us-east-1"
      anchor_table: blocks
      partition_cols:
        blocks: [block_timestamp]
      default_partition_cols: [block_time]

pipelines:
  my_pipeline:
    provider:
      name: my_sqd_provider
      config:
        format: evm
        query:
          from_block: 0 
          fields:
            block:
              number: true
            log:
              data: true
              topic0: true
              topic1: true
              topic2: true
              topic3: true
    
    steps:
      - name: my_validate_evm_event
        kind: evm_validate_block_data
      
      - name: my_decode_transfers
        kind: evm_decode_events
        config:
          event_signature: "Transfer(address,address,uint256)"
          input_table: "logs"
          output_table: "transfer_events"
          allow_decode_fail: true

            
    writer:
      name: my_local_writer
      kind: local_parquet
      config:
        path: data
        database: xyz
