# Project name for reference
name: "my_project"

# Data source configuration
data_source:
  - kind: "hypersync"
    url: "https://eth.rpc.hypersync.xyz/"

# Block processing configuration
blocks:
  index_blocks: true
  include_transactions: true

# Transaction filtering configuration
transactions:
  address: []
  from: []
  to: []

# Traces processing
traces: false

# Contract and events processing configuration
events:
  - name: "USDT_Transfer"
    address: ["0xdAC17F958D2ee523a2206206994597C13D831ec7"]  # USDT contract
    topics: [["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]]  # Transfer event
    signature: "Transfer(address indexed from,address indexed to,uint256 value)"

# Transformation configuration
transform:
  - kind: "Polars"

# Output configuration
output:
  - kind: "Postgres"
    url: "postgresql://postgres:postgres@localhost:5432/postgres"
  
