# Project name for reference
name: "my_project"

# Data source configuration
data_source:
  - kind: hypersync
    url: "https://eth.hypersync.xyz"

# Block processing configuration
blocks:
  index_blocks: true
  include_transactions: true

# Transaction filtering configuration
transactions:
  address: []
  from: []
  to: []

# Traces processing
traces: false

# Contract and events processing configuration
events:
  - name: Transfer
    signature: "Transfer(address indexed from, address indexed to, uint256 amount)"
    column_mapping: {amount: float64}

contract_identifier_signatures:
  - "Approval(address indexed _owner, address indexed _spender, uint256 _value)"

items_per_section: 30000

parquet_output_path: "data"

from_block: 21123123
to_block: null

# Transformation configuration
transform:
  - kind: "Polars"

# Output configuration
output:
  - kind: Postgres
    enabled: true
    url: "postgresql://postgres:postgres@localhost:5432/postgres"
  - kind: Parquet
    enabled: true
    output_dir: "data"
  - kind: S3
    enabled: true
    endpoint: "localhost:9000"  # MinIO server endpoint
    access_key: "minioadmin"
    secret_key: "minioadmin"
    bucket: "blockchain-data"
    secure: false
  
