[project]
name = "cherry-etl"
version = "0.0.1"
description = "Library for building blockchain pipelines"
readme = "README.md"
license = "MIT OR Apache-2.0"
authors = [
  { name = "Enes Topuz", email = "tpzenes@gmail.com" },
  { name = "Ozgur Akkurt", email = "oezgurmakkurt@gmail.com" },
]
requires-python = ">=3.10"
dependencies = [
    "cherry-core>=0.0.14",
    "clickhouse-connect>=0.8.15",
    "pyarrow>=19.0.1",
    "pyiceberg>=0.8.1",
]

[dependency-groups]
dev = [
    "psycopg2>=2.9.10",
    "ruff>=0.9.7",
    "sqlalchemy>=2.0.38",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/cherry"]

